<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- CSRF Token -->
		    <meta name="csrf-token" content="{{ csrf_token() }}">

        <title>@yield('title')</title>
        <meta name="Description" content="Anne Arundel Properties specializes in residential and commercial Real Estate services throughout Anne Arundel County, Maryland. Our experienced agents cover any of your home buying needs from foreclosures to water front.">
        <meta name="Keywords" content="anne arundel properties, Real Estate Agents annapolis, real estate company maryland, real estate agents anne arundel maryland">

        <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
        <script type="application/ld+json">
        {
          "@context" : "http://schema.org",
          "@type" : "LocalBusiness",
          "name" : "Taylor Properties",
          "image" : "{{ asset('images/logos/AnneArundelProperties.png') }}",
          "telephone" : "800-477-5191",
          "address" : {
            "@type" : "PostalAddress",
            "streetAddress" : "175 Admiral Cochrane Drive, Suite 111-112",
            "addressLocality" : "Annapolis",
            "addressRegion" : "MD",
            "postalCode" : "21401"
          },
          "openingHoursSpecification" : {
            "@type" : "OpeningHoursSpecification",
            "dayOfWeek" : {
              "@type" : "DayOfWeek",
              "name" : "Monday - Friday"
            }
          },
          "url" : "www.taylorproperties.co"
        }
        </script>

        <link rel="shortcut icon" href="{{ asset('favicon.png') }}">
    		<link rel="icon" type="image/png" href="{{ asset('favicon.png') }}">
    		<link rel="stylesheet" href="{{ asset('css/app.css') }}">
    		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
		    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    </head>
    <body>
    	@include('includes.navbar')

   		@yield('content')

      @include('includes.featured_listings')

    	<!-- Scripts -->
    	<script src="{{ asset('js/app.js') }}"></script>
    </body>

    @include('includes.footer')
</html>